replicaCount: 1

imagePullSecrets: []

image:
  repository: loctrec-auth
  tag: ""
  pullPolicy: IfNotPresent

gateway:
  host: "20.103.7.163.nip.io"

service:
  port: 8081

env:
  PORT: "8081"
  DATABASE_URL: "postgres://loctrec:loctrec@postgres-postgresql:5432/loctrec?sslmode=disable"
  GOOGLE_REDIRECT_URI: "https://20.103.7.163.nip.io/api/auth/oauth/google/callback"

secrets:
  JWT_PRIVATE_KEY: ""
  JWT_PUBLIC_KEY: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""

resources:
  requests:
    memory: 32Mi
    cpu: 10m
  limits:
    memory: 128Mi
    cpu: 250m
