version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /services/auth
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /services/events
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/client-sdk
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /services/tracker
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/auth
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/events
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /services/tracker
    schedule:
      interval: weekly
