replicaCount: 1

imagePullSecrets: []

image:
  repository: loctrec-tracker
  tag: ""
  pullPolicy: IfNotPresent

gateway:
  host: "20.103.7.163.nip.io"

service:
  port: 8083

env:
  PORT: "8083"
  AUTH_SERVICE_URL: "http://auth:8081"
  AUTH_JWKS_URL: "http://auth:8081/.well-known/jwks.json"

resources:
  requests:
    memory: 16Mi
    cpu: 10m
  limits:
    memory: 64Mi
    cpu: 250m
