apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  hosts:
    - {{ .Values.gateway.host | quote }}
  gateways:
    - loctrec-gateway
  http:
    - match:
        - uri:
            prefix: /api/auth/
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
    - match:
        - uri:
            exact: /api/auth
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ .Chart.Name }}
            port:
              number: {{ .Values.service.port }}
