apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loctrec-tls
  namespace: istio-system
spec:
  secretName: loctrec-tls
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
  dnsNames:
    - 20.103.7.163.nip.io
